# Description: Initial version of AWS CloudFormation template to create a VPC spanning 3 AZs in US-West-2
# Revision number: 1.0
# Date: 2025-03-30
AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS CloudFormation template to create a VPC spanning 3 AZs in US-West-2'

Resources:
  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: VPC-mahsut3848

  Subnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: us-west-2a
      Tags:
        - Key: Name
          Value: Subnet-1

  Subnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: us-west-2b
      Tags:
        - Key: Name
          Value: Subnet-2

  Subnet3:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: 10.0.3.0/24
      AvailabilityZone: us-west-2c
      Tags:
        - Key: Name
          Value: Subnet-3

Outputs:
  VPCId:
    Description: 'VPC ID'
    Value: !Ref MyVPC
